site_name: DevHub Python SDK
site_description: Python SDK for DevHub API
site_url: https://devotel.github.io/devhub-python/
repo_url: https://github.com/devotel/devhub-python
repo_name: devotel/devhub-python

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - SDK Reference:
    - SMS: sdk/sms.md
    - Email: sdk/email.md
    - WhatsApp: sdk/whatsapp.md
    - RCS: sdk/rcs.md
    - Contacts: sdk/contacts.md
    - Contact Groups: sdk/contact_groups.md
  - Examples: examples.md
  - Error Handling: error_handling.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_category_heading: true
